### ISSUE TITLE
Download of image_data.json file

### ISSUE THREAD

**Issue by richardvogg** [liuhengyue/fcsgg#2]
Hi, thanks for sharing the code to this interesting method. 
I was wondering if (and if yes, where) I can find the VG-SGG-dicts.json and image_data.json file for download?

Thanks!

**Comment by liuhengyue** [comment]
Sorry, it is `VG-SGG-dicts-with-attri.json` instead of `VG-SGG-dicts.json`. I will correct this in the readme.
Both files are located in https://github.com/liuhengyue/fcsgg/tree/master/datasets/vg.

**Comment by richardvogg** [comment]
Thanks for the quick reply. It was my mistake, for some reason I assumed that these files also had to be downloaded from somewhere. Found them now.
