### ISSUE TITLE
Model weights not found

### ISSUE THREAD

**Issue by richardvogg** [liuhengyue/fcsgg#3]
When I run the quick training example

python tools/train_net.py \ 
--num-gpus 1 \
--config-file configs/quick_schedules/Quick-FCSGG-HRNet-W32.yaml

I get the following error:
FileNotFoundError: [Errno 2] No such file or directory: 'output/FasterR-CNN-HR32-3x.pth'

Do I have to download these weights from somewhere? I looked at the pytorch model zoo and also detectrons model zoo, but did not find the file. When I exchange Quick-FCSGG-HRNet-W32.yaml with another configuration, I run into similar problems.

**Comment by liuhengyue** [comment]
The pre-trained weights can be downloaded from https://github.com/HRNet/HRNet-MaskRCNN-Benchmark. You can simply change the configuration file to start without the weight file, please refer to Detectron2.
