### ISSUE TITLE
How to test the custom images? / Visualize the generated scene graph for the custom images

### ISSUE THREAD

**Issue by dyang-TUM** [liuhengyue/fcsgg#4]
Hi, @liuhengyue  could you please provide the way to test the custom images and visualize the generated scene graph after training? It seems like I need to use visualize_output.py.

Thanks for your help!

**Comment by liuhengyue** [comment]
For testing images from the dataloader, you can use the script tools/visualize_output.py, and tools/custom_predict.py for custom images.
