### ISSUE TITLE
Scene graphs url seems to be broken

### ISSUE THREAD

**Issue by 20001LastOrder** [liuhengyue/fcsgg#7]
Hi, it seems that the url for [scene graphs](https://onedrive.live.com/embed?cid=22376FFAD72C4B64&resid=22376FFAD72C4B64%21779871&authkey=AA33n7BRpB1xa3I) is broken (I got 'Sorry, something went wrong). Could you check the link to see if it still works? Thank you!

**Comment by liuhengyue** [comment]
Fixed it! You can refer to https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch if it stops working again in the future.
